name: CI
on:
  push: { branches: [main] }
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Install Solana + Anchor
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          npm i -g @coral-xyz/anchor-cli
      - run: anchor build

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r client_py/requirements.txt pytest
      - name: Lint (basic syntax)
        run: python -m py_compile $(git ls-files '*.py')
